--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/amos-wallpapers/wallhaven-k716w7_1920x1080.jpg"

-- Special
background="#100a1e"
foreground="#a5bedc"
cursor="#a5bedc"

-- Colors
color0="#100a1e"
color1="#AE4870"
color2="#4F519A"
color3="#5C5697"
color4="#9E579F"
color5="#D55DA0"
color6="#BF6BD0"
color7="#a5bedc"
color8="#73859a"
color9="#AE4870"
color10="#4F519A"
color11="#5C5697"
color12="#9E579F"
color13="#D55DA0"
color14="#BF6BD0"
color15="#a5bedc"
