# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/amos-wallpaper-v3/024.jpg'

# Special
background='#030C15'
foreground='#99dddf'
cursor='#99dddf'

# Colors
color0='#030C15'
color1='#574A4D'
color2='#C64C3D'
color3='#0A7588'
color4='#517B85'
color5='#0899A6'
color6='#16D4D6'
color7='#99dddf'
color8='#6b9a9c'
color9='#574A4D'
color10='#C64C3D'
color11='#0A7588'
color12='#517B85'
color13='#0899A6'
color14='#16D4D6'
color15='#99dddf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
