# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/amos-wallpaper-v3/036.jpg'

# Special
background='#010C11'
foreground='#c2c9f3'
cursor='#c2c9f3'

# Colors
color0='#010C11'
color1='#1667DF'
color2='#1072F1'
color3='#827EDA'
color4='#0197B3'
color5='#05A3D9'
color6='#3DB1E2'
color7='#c2c9f3'
color8='#878caa'
color9='#1667DF'
color10='#1072F1'
color11='#827EDA'
color12='#0197B3'
color13='#05A3D9'
color14='#3DB1E2'
color15='#c2c9f3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
