--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/amos-wallpaper-v3/024.jpg"

-- Special
background="#030C15"
foreground="#99dddf"
cursor="#99dddf"

-- Colors
color0="#030C15"
color1="#574A4D"
color2="#C64C3D"
color3="#0A7588"
color4="#517B85"
color5="#0899A6"
color6="#16D4D6"
color7="#99dddf"
color8="#6b9a9c"
color9="#574A4D"
color10="#C64C3D"
color11="#0A7588"
color12="#517B85"
color13="#0899A6"
color14="#16D4D6"
color15="#99dddf"
