# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/amos-wallpaper-v3/57.jpg'

# Special
background='#101118'
foreground='#c3c8ed'
cursor='#c3c8ed'

# Colors
color0='#101118'
color1='#4144AB'
color2='#4B5AAD'
color3='#596ACF'
color4='#966BA2'
color5='#788498'
color6='#7688E2'
color7='#c3c8ed'
color8='#888ca5'
color9='#4144AB'
color10='#4B5AAD'
color11='#596ACF'
color12='#966BA2'
color13='#788498'
color14='#7688E2'
color15='#c3c8ed'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
