--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/amos-wallpaper-v3/036.jpg"

-- Special
background="#010C11"
foreground="#c2c9f3"
cursor="#c2c9f3"

-- Colors
color0="#010C11"
color1="#1667DF"
color2="#1072F1"
color3="#827EDA"
color4="#0197B3"
color5="#05A3D9"
color6="#3DB1E2"
color7="#c2c9f3"
color8="#878caa"
color9="#1667DF"
color10="#1072F1"
color11="#827EDA"
color12="#0197B3"
color13="#05A3D9"
color14="#3DB1E2"
color15="#c2c9f3"
